version: '3'

services:
  hmtm_bff:
    container_name: hmtm_bff
    image: d3m0s/hmtm_bff:latest
    ports:
      - "${HMTM_BFF_OUTER_PORT}:${HMTM_BFF_INNER_PORT}"
    env_file:
      - .env.bff
    depends_on:
      - hmtm_sso
      - hmtm_toys
    volumes:
      - ./logs/hmtm_bff:/app/logs

  hmtm_sso:
    container_name: hmtm_sso
    image: d3m0s/hmtm_sso:latest
    ports:
      - "${HMTM_SSO_OUTER_PORT}:${HMTM_SSO_INNER_PORT}"
    env_file:
      - .env.sso
    depends_on:
      - hmtm_sso_database
    volumes:
      - ./logs/hmtm_sso:/app/logs

  hmtm_sso_database:
    container_name: hmtm_sso_database
    hostname: hmtm_sso_database
    image: postgres
    restart: always
    env_file:
      - .env.sso
    volumes:
      - ./postgres_data/hmtmsso:/var/lib/postgresql/data
      - ./postgres_backups/hmtmsso:/backups
    ports:
      - "${HMTM_SSO_DB_OUTER_PORT}:${HMTM_SSO_DB_INNER_PORT}"

  hmtm_toys:
    container_name: hmtm_toys
    image: d3m0s/hmtm_toys:latest
    ports:
      - "${HMTM_TOYS_OUTER_PORT}:${HMTM_TOYS_INNER_PORT}"
    env_file:
      - .env.toys
    depends_on:
      - hmtm_toys_database
    volumes:
      - ./logs/hmtm_toys:/app/logs

  hmtm_toys_database:
    container_name: hmtm_toys_database
    hostname: hmtm_toys_database
    image: postgres
    restart: always
    env_file:
      - .env.toys
    volumes:
      - ./postgres_data/hmtm_toys:/var/lib/postgresql/data
      - ./postgres_backups/hmtm_toys:/backups
    ports:
      - "${HMTM_TOYS_DB_OUTER_PORT}:${HMTM_TOYS_DB_INNER_PORT}"
